BandMember.create(name: "Brian May", original_band: "Queen", skill_points: 9, instrument: "guitar")
BandMember.create(name: "Yngwie Malmsteen", original_band: "Yngwie Malmsteen", skill_points: 10, instrument: "guitar")
BandMember.create(name: "Jimmy Page", original_band: "Led Zepplin", skill_points: 7, instrument: "guitar")
BandMember.create(name: "Slash", original_band: "Guns N' Roses", skill_points: 7, instrument: "guitar")
BandMember.create(name: "Jimmy Hendrix", original_band: "Jimmy Hendrix", skill_points: 9, instrument: "guitar")
BandMember.create(name: "Dimebag Darrell", original_band: "Pantera", skill_points: 8, instrument: "guitar")
BandMember.create(name: "Eddie Van Halen", original_band: "Van Halen", skill_points: 9, instrument: "guitar")
BandMember.create(name: "Dave Mustaine", original_band: "Megadeath", skill_points: 6, instrument: "guitar")
BandMember.create(name: "Zakk Wylde", original_band: "Zakk Wylde Band", skill_points: 8, instrument: "guitar")
BandMember.create(name: "Synyster Gates", original_band: "Avenged Sevenfold", skill_points: 8, instrument: "guitar")

BandMember.create(name: "Tom Araya", original_band: "Slayer", skill_points: 7, instrument: "bass")
BandMember.create(name: "Troy Sanders", original_band: "Mastodon", skill_points: 8, instrument: "bass")
BandMember.create(name: "Flea", original_band: "Red Hot Chilli Peppers", skill_points: 8, instrument: "bass")
BandMember.create(name: "Robert Trujillo", original_band: "Metallica", skill_points: 7, instrument: "bass")
BandMember.create(name: "Les Claypool", original_band: "Primus", skill_points: 8, instrument: "bass")
BandMember.create(name: "John Myung", original_band: "Dream Theater", skill_points: 9, instrument: "bass")
BandMember.create(name: "Steve Harris", original_band: "Iron Maiden", skill_points: 9, instrument: "bass")
BandMember.create(name: "Dan Briggs", original_band: "Between the Buried and Me", skill_points: 10, instrument: "bass")
BandMember.create(name: "Paul Gray", original_band: "Slipknot", skill_points: 7, instrument: "bass")
BandMember.create(name: "Lemmy", original_band: "Motorhead", skill_points: 8, instrument: "bass")

BandMember.create(name: "Travis Barker", original_band: "Blink 182", skill_points: 7, instrument: "drums")
BandMember.create(name: "Alex Van Halen", original_band: "Van Halen", skill_points: 8, instrument: "drums")
BandMember.create(name: "Mike Portney", original_band: "Dream Theater", skill_points: 10, instrument: "drums")
BandMember.create(name: "Neil Peart", original_band: "Rush", skill_points: 8, instrument: "drums")
BandMember.create(name: "Chris Adler", original_band: "Lamb of God", skill_points: 7, instrument: "drums")
BandMember.create(name: "John Bonham", original_band: "Led Zepplin", skill_points: 8, instrument: "drums")
BandMember.create(name: "Joey Jordison", original_band: "Slipknot", skill_points: 9, instrument: "drums")
BandMember.create(name: "Vinnie Paul", original_band: "Pantera", skill_points: 7, instrument: "drums")
BandMember.create(name: "Tomas Haak", original_band: "Meshuggah", skill_points: 9, instrument: "drums")
BandMember.create(name: "Jason Costa", original_band: "All That Remains", skill_points: 9, instrument: "drums")

BandMember.create(name: "Paul McCartney", original_band: "The Beatles", skill_points: 9, instrument: "microphone")
BandMember.create(name: "Axl Rose", original_band: "Guns N' Roses", skill_points: 8, instrument: "microphone")
BandMember.create(name: "Steven Tyler", original_band: "Aerosmith", skill_points: 9, instrument: "microphone")
BandMember.create(name: "Rob Halford", original_band: "Judas Priest", skill_points: 7, instrument: "microphone")
BandMember.create(name: "Amy Lee", original_band: "Evanescence", skill_points: 8, instrument: "microphone")
BandMember.create(name: "Freddy Mercury", original_band: "Queen", skill_points: 9, instrument: "microphone")
BandMember.create(name: "Mick Jagger", original_band: "The Rolling Stones", skill_points: 7, instrument: "microphone")
BandMember.create(name: "Stevie Nicks", original_band: "Fleetwood Mac", skill_points: 7, instrument: "microphone")
BandMember.create(name: "Ozzy Osbourne", original_band: "Black Sabbath", skill_points: 8, instrument: "microphone")
BandMember.create(name: "Chester Bennington", original_band: "Linkin Park", skill_points: 10, instrument: "microphone")

BandMember.create(name: "Richard Wright", original_band: "Pink Floyd", skill_points: 10, instrument: "piano")
BandMember.create(name: "Elton John", original_band: "Elton John", skill_points: 8, instrument: "piano")
BandMember.create(name: "Michael Pinella", original_band: "Symphony X", skill_points: 8, instrument: "piano")
BandMember.create(name: "Janne Wirman", original_band: "Children of Bodom", skill_points: 9, instrument: "piano")
BandMember.create(name: "Ray Charles", original_band: "Ray Charles", skill_points: 6, instrument: "piano")
BandMember.create(name: "Vadim Pruzhanov", original_band: "DragonForce", skill_points: 9, instrument: "piano")
BandMember.create(name: "Jon Lord", original_band: "Deep Purple", skill_points: 8, instrument: "piano")
BandMember.create(name: "Billy Joel", original_band: "Billy Joel", skill_points: 8, instrument: "piano")
BandMember.create(name: "Jordan Rudus", original_band: "Dream Theater", skill_points: 9, instrument: "piano")
BandMember.create(name: "Stevie Wonder", original_band: "Stevie Wonder", skill_points: 7, instrument: "piano")
