# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Guitarist.create(name: "Brian May", original_band: "Queen", skill_points: )
Guitarist.create(name: "Yngwie Malmsteen", original_band: "Yngwie Malmsteen", skill_points: )
Guitarist.create(name: "Jimmy Page", original_band: "Led Zepplin", skill_points: )
Guitarist.create(name: "Slash", original_band: "Guns and Roses", skill_points: )
Guitarist.create(name: "Randy Rhoads", original_band: "Ozzy Osbourne", skill_points: )
Guitarist.create(name: "Dimebag Darrell", original_band: "Pantera", skill_points: )
Guitarist.create(name: "Eddie Van Halen", original_band: "Van Halen", skill_points: )
Guitarist.create(name: "Dave Mustaine", original_band: "Megadeath", skill_points: )
Guitarist.create(name: "Zakk Wylde", original_band: "Zakk Wylde Band", skill_points: )
Guitarist.create(name: "Synyster Gates", original_band: "Avenged Sevenfold", skill_points: )

Bassist.create(name: "Tom Araya" original_band: "Slayer", skill_points: )
Bassist.create(name: "Troy Sanders" original_band: "Mastodon", skill_points: )
Bassist.create(name: "Flea" original_band: "Red Hot Chilli Peppers", skill_points: )
Bassist.create(name: "Robert Trujillo" original_band: "Metallica", skill_points: )
Bassist.create(name: "Les Claypool" original_band: "Primus", skill_points: )
Bassist.create(name: "John Myung" original_band: "Dream Theater", skill_points: )
Bassist.create(name: "Steve Harris" original_band: "Iron Maiden", skill_points: )
Bassist.create(name: "Dan Briggs" original_band: "Between the Buried and Me", skill_points: )
Bassist.create(name: "Paul Gray" original_band: "Slipknot", skill_points: )
Bassist.create(name: "Gene Simmons" original_band: "KISS", skill_points: )

Drummer.create(name: "Travis Barker" original_band: "Blink 182", skill_points: )
Drummer.create(name: "Alex Van Halen" original_band: "Van Halen", skill_points: )
Drummer.create(name: "Mike Portney" original_band: "Dream Theater", skill_points: )
Drummer.create(name: "Neil Peart" original_band: "Rush", skill_points: )
Drummer.create(name: "Chris Adler" original_band: "Lamb of God", skill_points: )
Drummer.create(name: "Meg White" original_band: "White Stripes", skill_points: )
Drummer.create(name: "Danny Cary" original_band: "Tool", skill_points: )
Drummer.create(name: "Vinnie Paul" original_band: "Pantera", skill_points: )
Drummer.create(name: "Tomas Haak" original_band: "Meshuggah", skill_points: )
Drummer.create(name: "Paul Mazurkiewicz" original_band: "Cannibal Corpse", skill_points: )

Singer.create(name: "Steven Tyler", original_band: "Aerosmith", skill_points: 9)
Singer.create(name: "Rob Halford", original_band: "Judas Priest", skill_points: 7)
Singer.create(name: "Maynard James Keenan", original_band: "Tool", skill_points: 7)
Singer.create(name: "Freddy Mercury", original_band: "Queen", skill_points: 10)
Singer.create(name: "Mick Jagger", original_band: "The Rolling Stones", skill_points: 7)
Singer.create(name: "Stevie Nicks", original_band: "Fleetwood Mac", skill_points: 8)
Singer.create(name: "Paul McCartney", original_band: "The Beatles", skill_points: 9)
Singer.create(name: "Roger Daltrey", original_band: "The Who", skill_points: 7)
Singer.create(name: "John Fogerty", original_band: "Creedence Clearwater Revival", skill_points: 5)
Singer.create(name: "Joan Jett", original_band: "Joan Jett & The Blackhearts", skill_points: 7)

Pianist.create(name: "Elton John" original_band: "Elton John", skill_points: 8)
Pianist.create(name: "Billy Joel" original_band: "Billy Joel", skill_points: 8)
Pianist.create(name: "Ray Charles" original_band: "Ray Charles", skill_points: 6)
Pianist.create(name: "Stevie Wonder" original_band: "Stevie Wonder", skill_points: 7)
Pianist.create(name: "Jordan Rudus" original_band: "Dream Theater", skill_points: 10)
Pianist.create(name: "Vadim Pruzhanov" original_band: "DragonForce", skill_points: 9)
Pianist.create(name: "Jon Lord" original_band: "Deep Purple", skill_points: 8)
Pianist.create(name: "Janne Wirman" original_band: "Children of Bodom", skill_points: 9)
Pianist.create(name: "Christian Flake Lorenz" original_band: "Elton John", skill_points: 7)
Pianist.create(name: "Michael Pinella" original_band: "Symphony X", skill_points: 8)
